Repository scutcs3/codeview, pull requests merged in 2021-05, with the labels that each got.

#9 添加vue路由
  README.md
  backend/package-lock.json
  doc/环境搭建.md
  frontend/package-lock.json
  frontend/src/App.vue
  frontend/src/main.js
  frontend/src/pages/Index.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Viewee.vue
  frontend/src/pages/Viewer.vue
  frontend/src/routes.js
  package-lock.json
Labels: enhancement

#15 Feature/editor
  README.md
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Editor.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/components/Problem.vue
  frontend/src/components/monacoEditor.vue
  frontend/src/pages/Viewee.vue
  frontend/src/plugins/element.js
  frontend/vue.config.js
Labels: 需求

#18 Feature/static page
  .github/workflows/Page.yml
  frontend/package.json
  frontend/vue.config.js
Labels: 构建

#19 添加登录页面
  frontend/package-lock.json
  frontend/src/pages/Login.vue
  frontend/src/plugins/element.js
Labels: 需求

#21 Feature/mysql
  backend/app.js
  backend/config/mysql.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/problems.js
  backend/routes/users.js
  frontend/babel.config.js
  frontend/src/App.vue
  frontend/src/components/Editor.vue
  frontend/src/components/Problem.vue
  frontend/src/components/monacoEditor.vue
  frontend/src/pages/Index.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Viewee.vue
  frontend/src/pages/Viewer.vue
  frontend/src/routes.js
Labels: 需求

#27 add sql file
  backend/config/comment.sql
  backend/config/interview.sql
  backend/config/problem.sql
  backend/config/user.sql
Labels: 设计

#29 面试官界面添加
  .github/workflows/Page.yml
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/Editor.vue
  frontend/src/components/add.vue
  frontend/src/pages/Register.vue
  frontend/src/pages/Viewer.vue
  frontend/src/routes.js
Labels: 前端, 需求

#26 Feature/register
  frontend/src/pages/Register.vue
Labels: 前端, 需求

#36 Feature/api
  .github/workflows/Page.yml
  .gitignore
  api/README.md
  api/openapi.yaml
  package-lock.json
Labels: 设计

#40 fix mysql connect bug :bug:
  backend/routes/problems.js
Labels: 后端, 缺陷

#42 Feature/login logic
  frontend/src/App.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Register.vue
Labels: 前端, 需求

#45 加入网页基本布局
  frontend/src/App.vue
  frontend/src/components/Foot.vue
  frontend/src/components/Head.vue
  frontend/src/components/Menu.vue
  frontend/src/layouts/Layout.vue
  frontend/src/layouts/Main.vue
  frontend/src/main.css
  frontend/src/main.js
  frontend/src/pages/Console.vue
  frontend/src/pages/Index.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Register.vue
  frontend/src/pages/Viewer.vue
Labels: 前端, 需求

#48 Feature/overview
  frontend/src/components/Comment.vue
  frontend/src/components/Head.vue
  frontend/src/components/Problem.vue
  frontend/src/layouts/Layout.vue
  frontend/src/pages/Console.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Overview.vue
  frontend/src/pages/Problems.vue
  frontend/src/pages/Profile.vue
  frontend/src/pages/Settings.vue
  frontend/src/pages/Viewee.vue
  frontend/src/pages/Viewer.vue
  frontend/src/plugins/element.js
  frontend/src/routes.js
Labels: 前端, 需求

#50 添加题库表格
  api/openapi.yaml
  frontend/package.json
  frontend/src/main.js
  frontend/src/mock.js
  frontend/src/pages/Problems.vue
  frontend/src/plugins/element.js
Labels: 前端, 需求

#51 Feature/overview
  api/openapi.yaml
Labels: 设计

#58 Feature/overview
  frontend/package.json
  frontend/src/App.vue
  frontend/src/api/global.js
  frontend/src/api/problem.js
  frontend/src/api/user.js
  frontend/src/components/Document.vue
  frontend/src/components/Head.vue
  frontend/src/components/Menu.vue
  frontend/src/components/add.vue
  frontend/src/main.js
  frontend/src/mock.js
  frontend/src/pages/Console.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Overview.vue
  frontend/src/pages/Problem.vue
  frontend/src/pages/Problems.vue
  frontend/src/pages/Register.vue
  frontend/src/pages/Settings.vue
  frontend/src/pages/Viewee.vue
  frontend/src/plugins/element.js
  frontend/src/router.js
  frontend/src/store.js
Labels: 前端, 需求

#63 修复构建错误
  .github/workflows/Page.yml
Labels: 构建, 缺陷

#75 合并数据库建表文件
  backend/config/answer.sql
  backend/config/comment.sql
  backend/config/interview.sql
  backend/config/interview_problem.sql
  backend/config/problem.sql
  backend/config/table.sql
  backend/config/user.sql
Labels: 后端, 测试, 缺陷

#76 Feature/test
  backend/app.js
  backend/routes/answers.js
  backend/routes/comments.js
  backend/routes/interviews.js
  backend/routes/problems.js
  backend/routes/users.js
  backend/test/answers.test.js
  backend/test/comments.test.js
  backend/test/interviews.test.js
  backend/test/problems.test.js
  backend/test/users.test.js
Labels: 后端, 测试, 缺陷

#78 添加富文本功能 实时聊天界面及功能
  backend/package.json
  backend/routes/problems.js
  backend/server.js
  frontend/package.json
  frontend/public/tinymce/langs/zh_CN.js
  frontend/public/tinymce/skins/content/dark/content.css
  frontend/public/tinymce/skins/content/dark/content.min.css
  frontend/public/tinymce/skins/content/default/content.css
  frontend/public/tinymce/skins/content/default/content.min.css
  frontend/public/tinymce/skins/content/document/content.css
  frontend/public/tinymce/skins/content/document/content.min.css
  frontend/public/tinymce/skins/content/writer/content.css
  frontend/public/tinymce/skins/content/writer/content.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.inline.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.inline.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.mobile.css
  frontend/public/tinymce/skins/ui/oxide-dark/content.mobile.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/fonts/tinymce-mobile.woff
  frontend/public/tinymce/skins/ui/oxide-dark/skin.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.mobile.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.mobile.min.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.shadowdom.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.shadowdom.min.css
  frontend/public/tinymce/skins/ui/oxide/content.css
  frontend/public/tinymce/skins/ui/oxide/content.inline.css
  frontend/public/tinymce/skins/ui/oxide/content.inline.min.css
  frontend/public/tinymce/skins/ui/oxide/content.min.css
  frontend/public/tinymce/skins/ui/oxide/content.mobile.css
  frontend/public/tinymce/skins/ui/oxide/content.mobile.min.css
  frontend/public/tinymce/skins/ui/oxide/fonts/tinymce-mobile.woff
  frontend/public/tinymce/skins/ui/oxide/skin.css
  frontend/public/tinymce/skins/ui/oxide/skin.min.css
  frontend/public/tinymce/skins/ui/oxide/skin.mobile.css
  frontend/public/tinymce/skins/ui/oxide/skin.mobile.min.css
  frontend/public/tinymce/skins/ui/oxide/skin.shadowdom.css
  frontend/public/tinymce/skins/ui/oxide/skin.shadowdom.min.css
  frontend/src/components/AddProblem.vue
  frontend/src/components/BaseComment.vue
  frontend/src/components/TinymceEditor.vue
  frontend/src/pages/VieweePage.vue
  frontend/src/plugins/element.js
Labels: 前端

#80 优化webhook脚本
  backend/webhook.js
  frontend/src/main.js
  frontend/vue.config.js
Labels: 构建

#101 hashids for interview url
  backend/package.json
  backend/routes/interviews.js
  backend/routes/problems.js
Labels: 后端, 缺陷, 需求

#106 Feature/api
  config/table.sql
  package-lock.json
  routes/problems.js
Labels: 后端, 缺陷, 设计

#112 Feature/problems
  .eslintrc.js
  app.js
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  routes/answers.js
  routes/comments.js
  routes/interviews.js
  routes/problems.js
  routes/users.js
  src/api/global.js
  src/api/problem.js
  src/pages/InterviewsListPage.vue
  src/pages/ProblemPage.vue
  src/pages/ProblemsListPage.vue
  src/pages/ProblemsNewPage.vue
  src/pages/ProblemsPage.vue
  src/plugins/element.js
  vue.config.js
Labels: 前端, 需求
